version: '3.8'    #check if there is a new docker compose version
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "5672:5672"
      - "8000:15672"
    command: "/bin/bash -c \"rabbitmq-plugins enable --offline rabbitmq_mqtt; rabbitmq-server\""
    env_file:
      - ./_login.env
    volumes:
      - type: bind
        source: ./_rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
        read_only: true
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      interval: 1s
      timeout: 1s
      retries: 10
